# Generated by Django 5.1.1 on 2024-10-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientdata_created_at_patientdata_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
