# Generated by Django 5.1.2 on 2024-10-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_doctordata_oxygen_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='weight',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitalhistorydoctor',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitalhistorydoctor',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitalhistorypatient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitalhistorypatient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_type',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Portable', 'Portable')], max_length=50),
        ),
    ]
