# Generated by Django 5.1.1 on 2024-10-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_patientdata_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
