# Generated by Django 5.1.2 on 2024-11-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_doctorprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='charak_id',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='charak_id',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
