# Generated by Django 5.1.1 on 2024-10-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_patientdata_temperature_doctordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
