# Generated by Django 5.1.1 on 2024-10-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='respiratory_rate',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='glucose_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='glucose_samples',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='oxygen_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='glucose_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='glucose_samples',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='oxygen_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='heart_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='spo2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='heart_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='spo2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
