# Generated by Django 5.1.2 on 2024-11-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctorprofile_charak_id_patientprofile_charak_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='charak_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='charak_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
