# Generated by Django 5.1.2 on 2024-11-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_doctorprofile_charak_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='charak_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='charak_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
